// Test generated by RoostGPT for test bb using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class ProductController_createProduct_5fee6d5a95_Test {

    @InjectMocks
    ProductController productController;

    @Mock
    ProductRepository productRepository;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testCreateProduct() {
        Product product = new Product();
        product.setId(1L); // Changed from integer to Long
        product.setName("Test Product");
        product.setDescription("Test Product Description");
        product.setPrice(100.0);

        when(productRepository.save(product)).thenReturn(product);

        Product result = productController.createProduct(product);

        assertEquals(product, result);
    }

    @Test
    public void testCreateProduct_nullProduct() {
        Product product = null;

        when(productRepository.save(product)).thenReturn(product);

        Product result = productController.createProduct(product);

        assertEquals(product, result);
    }
}
